# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Identificador único', max_length=32, unique=True, verbose_name='SKU')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en soles con dos decimales como máximo.', max_digits=12, verbose_name='Precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
            ],
            options={
                'ordering': ['sku'],
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
