# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nombre',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Identificador único', max_length=32, unique=True, verbose_name='SKU'),
        ),
    ]
