# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170103_1759'),
        ('quotes', '0002_quotereceiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Identificador único', max_length=32, unique=True, verbose_name='SKU')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en soles con dos decimales como máximo.', max_digits=12, verbose_name='Precio')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Subtotal')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Producto')),
            ],
            options={
                'verbose_name_plural': 'Productos a cotizar',
                'verbose_name': 'Producto a cotizar',
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Quote', verbose_name='Cotización'),
        ),
    ]
