# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20170103_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteproduct',
            name='sku',
            field=models.CharField(help_text='Identificador único', max_length=32, verbose_name='SKU'),
        ),
        migrations.AlterUniqueTogether(
            name='quoteproduct',
            unique_together=set([('quote', 'sku')]),
        ),
    ]
