# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20170107_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='igv',
            field=models.DecimalField(decimal_places=1, default=18, max_digits=3, verbose_name='IGV'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quoteproduct',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_a_cotizar', to='quotes.Quote', verbose_name='Cotización'),
        ),
    ]
