# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20170108_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='aplica_detraccion',
            field=models.BooleanField(default=False, verbose_name='Aplica Detracción'),
        ),
    ]
