# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_quote_aplica_detraccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='empresa_direccion',
            field=models.CharField(default='', max_length=180, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='empresa_razon_social',
            field=models.CharField(default='', max_length=180, verbose_name='Razón Social'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='empresa_telefono',
            field=models.CharField(blank=True, max_length=32, verbose_name='Teléfono de la empresa'),
        ),
    ]
