# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20170110_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='estado',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'PENDIENTE'), ('ENVIADA', 'ENVIADA'), ('APROBADA', 'APROBADA'), ('DENEGADA', 'DENEGADA'), ('CANCELADA', 'CANCELADA')], default='PENDIENTE', max_length=24, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='valida_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Válida hasta'),
        ),
    ]
