# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_auto_20170116_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='valida_hasta',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Válida hasta'),
        ),
    ]
