# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_auto_20170116_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='forma_de_pago',
            field=models.CharField(blank=True, max_length=180, verbose_name='Forma de pago'),
        ),
    ]
