# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='igv',
            field=models.DecimalField(decimal_places=1, default=18, max_digits=3, verbose_name='IGV'),
        ),
    ]
