# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoman', '0002_auto_20170103_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='razon_social',
            field=models.CharField(default='', max_length=120, verbose_name='Razón Social'),
        ),
    ]
