COTIZACION_PENDIENTE = 'PENDIENTE'
COTIZACION_APROBADA = 'APROBADA'
COTIZACION_DENEGADA = 'DENEGADA'
COTIZACION_CANCELADA = 'CANCELADA'

COTIZACION_ESTADO = (
    (COTIZACION_PENDIENTE, COTIZACION_PENDIENTE),
    (COTIZACION_APROBADA, COTIZACION_APROBADA),
    (COTIZACION_DENEGADA, COTIZACION_DENEGADA),
    (COTIZACION_CANCELADA, COTIZACION_CANCELADA),
)
