COTIZACION_PENDIENTE = 'PENDIENTE'
COTIZACION_ENVIADA = 'ENVIADA'
COTIZACION_APROBADA = 'APROBADA'  # DESPUÉS DE SER ENVIADA
COTIZACION_DENEGADA = 'DENEGADA'  # DESPUÉS DE SER ENVIADA
COTIZACION_CANCELADA = 'CANCELADA'

COTIZACION_ESTADO = (
    (COTIZACION_PENDIENTE, COTIZACION_PENDIENTE),
    (COTIZACION_ENVIADA, COTIZACION_ENVIADA),
    (COTIZACION_APROBADA, COTIZACION_APROBADA),
    (COTIZACION_DENEGADA, COTIZACION_DENEGADA),
    (COTIZACION_CANCELADA, COTIZACION_CANCELADA),
)
